### ISSUE TITLE
inline ellipsis location?

### ISSUE THREAD

**Issue by voodoo6** [jsillitoe/jquery-condense-plugin#3]
Hi, can anybody help me to figure out how to move the ellipsis (...) to output inline next to the truncated text? I need to have the 'more' link on its own line which I have done using css but i can't see how to move the '...' to append inline at the end of the truncated text?

<em>Here is an example of how I would like my finished text block to look (notice the different placement of the '...' :</em>
Example text lorem ipsum dolor ...
Read More

<em>but all I can get is:</em>
Example text lorem ipsum dolor
... Read More

Looking at the plugin code, I can't see where in the code I can change where the ellipsis is output?
Many Thanks for any help..

**Comment by jsillitoe** [comment]
Thanks.  I merged the patch.
